[tool.poetry]
name = "connect-four-lib"
version = "0.1.0"
description = "A library for connect 4 game"
authors = ["game-ai-platform-team"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
