name: Deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: game-ai-platform-team/setup-poetry@main
    
    - name: Configure PyPI Token
      run: poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

    - name: Build and publish to pypi
      run: poetry publish --build